apiVersion: v1
kind: Service
metadata:
  name: bank-app-mysql-service
spec:
  selector:
    app: bank-application-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30000  # Choose an available port number in the range of 30000-32767
  type: NodePort



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app-mysql-deployment
spec:
  selector:
    matchLabels:
      app: bank-application-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: bank-application-mysql
    spec:
      containers:
        - name: bank-application-mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts: 
          - mountPath: /log
            name: bank-db-claim
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: abc123
            - name: MYSQL_DATABASE
              value: abcbank
      volumes:
      - name: bank-db-claim
        persistentVolumeClaim:
         claimName: bank-app-db-claim-volume
         
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bank-app-db-claim-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi




        
