apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-app-frontend
  template:
    metadata:
      labels:
        app: bank-app-frontend
    spec:
      containers:
        - name: bank-app-frontend
          image: aruna451/reactbankapp:1.0.3
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://127.0.0.1:50430  # Replace with the appropriate URL/ backend service
---
apiVersion: v1
kind: Service
metadata:
  name: bank-app-frontend-service
spec:
  selector:
    app: bank-app-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
