apiVersion: v1
kind: PersistentVolume
metadata:
  name: bank-app-db-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath: 
    path: /dbdata/log
